### ISSUE TITLE
Erroneous "unexpected newline" after super call with no parentheses

### ISSUE THREAD

**Issue by zcoffin86** [lkytal/coffeelinter#5]
I'm not sure if this functionality is deprecated or otherwise discouraged in coffeescript in general, however it seems to still be valid so...

As discussed in various places (such as https://stackoverflow.com/questions/5953670/extend-class-and-pass-all-constructor-arguments-to-super), this is accepted syntax, therefore should not be flagged as a lint error?

http://recordit.co/MizXjMKQ3s
![2018-05-24 13_16_20- test coffee - untitled workspace - visual studio code](https://user-images.githubusercontent.com/32465097/40503733-b896766a-5f54-11e8-8383-d5b4854506f8.png)
![2018-05-24 13_16_36- test coffee - untitled workspace - visual studio code](https://user-images.githubusercontent.com/32465097/40503734-b8b66aec-5f54-11e8-984d-6e1076810f73.png)

**Comment by zcoffin86** [comment]
actually i guess this is a parse error. Bare super was apparently deprecated in CoffeeScript 2: https://coffeescript.org/#breaking-changes-super-extends. Strange though, I'm using the latest coffee script (2.3.0) and the arguments are actually passed... I'm already updating with the new syntax. Sorry for the confusion. Cheers!

**Comment by lkytal** [comment]
Thanks for your feedback I just notice it. You may find more info from the linter itself http://www.coffeelint.org/.
